version: '3.3'
services:
  tag_api: 1.0
    build: ./Demo3
    depends_on:
      - redis
      - postgres
    ports:
     - "6010:6010"
    links:
     - "redis:redis"
     - "postgres:postgres"

  redis:
    image: redis:latest
  postgres:
    image: postgres:latest
    environment: POSTGRES_PASSWORD=lukechen0419

